agent.sources = src
agent.channels = ch
agent.sinks = sink

# Source
agent.sources.src.type = exec
agent.sources.src.command = tail -F /home/bigdata/Desktop/weather_stream.json

# Channel
agent.channels.ch.type = memory
agent.channels.ch.capacity = 1000
agent.channels.ch.transactionCapacity = 100

# Kafka Sink
agent.sinks.sink.type = org.apache.flume.sink.kafka.KafkaSink
agent.sinks.sink.kafka.bootstrap.servers = localhost:9092
agent.sinks.sink.kafka.topic = weather_topic

# Bindings
agent.sources.src.channels = ch
agent.sinks.sink.channel = ch
